kind: ZarfInitConfig
apiVersion: zarf.dev/v1beta1
metadata:
  name: everything-zarf-package
  description: A zarf package with a non empty value for every key - this demonstrates the changes proposed by ZEP-0051
  version: v1.0.0
  uncompressed: false
  architecture: amd64
  annotations: # All of these are v1alpha1 fields that will be deprecated in favor of a choose your own adventure label map
    authors: cool-kidz
    documentation: https://my-package-documentation.com
    source: https://my-git-server/my-package
    url: https://my-package-website.com
    vendor: my-vendor
    image: https://my-image-url-to-use-in-deprecated-zarf-ui
    anyway-you-want-it: thats-the-way-you-need-it
  allowNamespaceOverride: true
build: # Everything here is created by Zarf not by users
  terminal: my-computer
  user: my-user
  architecture: amd64
  timestamp: 2021-09-01T00:00:00Z
  version: v1.0.0
  migrations:
    - scripts-to-actions
  registryOverrides:
    gcr.io: my-gcr.com
  differential: true
  flavor: cool-flavor
  versionRequirements:
  - version: v0.68.0
    reason: This package contains image archives which will only be recognized on v0.68.0+  
  aggregateChecksum: shasum # this is moved from .metadata
values:
  files:
    - values.yaml
  schema: values-schema.json
documentation:
  my-file: "file.md"  
components:
- name: a-component
  description: Zarf description
  optional: false # Component is required (default behavior)
  target:
    os: darwin
    architecture: amd64
    flavor: a-flavor # this will only be used when there are multiple components
  import:
    path: ABCD # Only path or URL will be used, not both
    url: oci://
  service: registry # one of: registry, seed-registry, injector, agent, git-server
  manifests:
  - name: manifest
    namespace: manifest-ns
    files:
    - a-file.yaml
    kustomizeAllowAnyDirectory: false
    kustomizations:
    - a-kustomization.yaml
    noWait: true
    serverSideApply: "auto"
    template: true # Enable go-template processing
  charts:
  - name: chart
    namespace: chart-ns
    releaseName: chart-release
    noWait: false
    valuesFiles:
    - values.yaml
    values:
    - sourcePath: ".app.name"
      targetPath: ".appName"
    schemaValidation: true
    serverSideApply: "auto"
    helmRepository: # Only one of helmRepository, git, oci, or local is allowed
      url: https://stefanprodan.github.io/podinfo
      name: podinfo # replaces repoName since it's only applicable in this situation
      version: 6.4.0
    git:
      url: https://github.com/stefanprodan/podinfo.git@6.4.0
      path: charts/podinfo
    oci:
      url: oci://ghcr.io/stefanprodan/charts/podinfo
      version: 6.4.0
    local:
      path: chart
  files:
  - source: source-file.txt
    target: target-file.txt
    shasum: shasum
    executable: false
    symlinks:
    - /path/to/symlink
    extractPath: /path/to/extract
    template: false # Disable go-template processing for this file
  images:
    - name: podinfo:v1
      source: "registry" # optional - registry is the default value
  imageArchives:
  - path: podinfo.tar
    images:
      - podinfo:local
  repositories:
  - https://github.com/zarf-dev/zarf
  actions:
    onCreate:
      defaults:
        mute: true
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        shell:
          darwin: sh
          linux: sh
          windows: powershell
      before:
      - mute: false
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        cmd: echo hello
        shell:
          darwin: sh
          linux: sh
          windows: powershell
        setVariables:
        - name: VAR
          sensitive: false
          autoIndent: true
          pattern: ".+"
          type: raw
        setValues:
          - key: .json
        description: action-description
        wait:
          cluster: # Only one of cluster / network can be used
            kind: pod
            name: my-pod
            namespace: pod-ns
            condition: ready
          network:
            protocol: http
            address: github.com
            code: 200
      onSuccess:
      - mute: false
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        cmd: echo hello
        shell:
          darwin: sh
          linux: sh
          windows: powershell
        setVariables:
        - name: VAR
          sensitive: false
          autoIndent: true
          pattern: ".+"
          type: raw
        setValues:
          - key: .json
        description: action-description
        wait:
          cluster: # Only one of cluster / network can be used
            kind: pod
            name: my-pod
            namespace: pod-ns
            condition: ready
          network:
            protocol: http
            address: github.com
            code: 200
      onFailure:
      - mute: false
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        cmd: echo hello
        shell:
          darwin: sh
          linux: sh
          windows: powershell
        setVariables:
        - name: VAR
          sensitive: false
          autoIndent: true
          pattern: ".+"
          type: raw
        setValues:
          - key: .json
        description: action-description
        wait:
          cluster: # Only one of cluster / network can be used
            kind: pod
            name: my-pod
            namespace: pod-ns
            condition: ready
          network:
            protocol: http
            address: github.com
            code: 200
    onDeploy:
      defaults:
        mute: true
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        shell:
          darwin: sh
          linux: sh
          windows: powershell
      before:
      - mute: false
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        cmd: echo hello
        shell:
          darwin: sh
          linux: sh
          windows: powershell
        setVariables:
        - name: VAR
          sensitive: false
          autoIndent: true
          pattern: ".+"
          type: raw
        setValues:
          - key: .json
        description: action-description
        wait:
          cluster: # Only one of cluster / network can be used
            kind: pod
            name: my-pod
            namespace: pod-ns
            condition: ready
          network:
            protocol: http
            address: github.com
            code: 200
      onSuccess:
      - mute: false
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        cmd: echo hello
        shell:
          darwin: sh
          linux: sh
          windows: powershell
        setVariables:
        - name: VAR
          sensitive: false
          autoIndent: true
          pattern: ".+"
          type: raw
        setValues:
          - key: .json
        description: action-description
        wait:
          cluster: # Only one of cluster / network can be used
            kind: pod
            name: my-pod
            namespace: pod-ns
            condition: ready
          network:
            protocol: http
            address: github.com
            code: 200
      onFailure:
      - mute: false
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        cmd: echo hello
        shell:
          darwin: sh
          linux: sh
          windows: powershell
        setVariables:
        - name: VAR
          sensitive: false
          autoIndent: true
          pattern: ".+"
          type: raw
        setValues:
          - key: .json
        description: action-description
        wait:
          cluster: # Only one of cluster / network can be used
            kind: pod
            name: my-pod
            namespace: pod-ns
            condition: ready
          network:
            protocol: http
            address: github.com
            code: 200
    onRemove:
      defaults:
        mute: true
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        shell:
          darwin: sh
          linux: sh
          windows: powershell
      before:
      - mute: false
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        cmd: echo hello
        shell:
          darwin: sh
          linux: sh
          windows: powershell
        setVariables:
        - name: VAR
          sensitive: false
          autoIndent: true
          pattern: ".+"
          type: raw
        setValues:
          - key: .json
        description: action-description
        wait:
          cluster: # Only one of cluster / network can be used
            kind: pod
            name: my-pod
            namespace: pod-ns
            condition: ready
          network:
            protocol: http
            address: github.com
            code: 200
      onSuccess:
      - mute: false
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        cmd: echo hello
        shell:
          darwin: sh
          linux: sh
          windows: powershell
        setVariables:
        - name: VAR
          sensitive: false
          autoIndent: true
          pattern: ".+"
          type: raw
        setValues:
          - key: .json
        description: action-description
        wait:
          cluster: # Only one of cluster / network can be used
            kind: pod
            name: my-pod
            namespace: pod-ns
            condition: ready
          network:
            protocol: http
            address: github.com
            code: 200
      onFailure:
      - mute: false
        maxTotalSeconds: 60
        retries: 0
        dir: dir
        env:
        - ENV_VAR=FOO
        cmd: echo hello
        shell:
          darwin: sh
          linux: sh
          windows: powershell
        setVariables:
        - name: VAR
          sensitive: false
          autoIndent: true
          pattern: ".+"
          type: raw
        setValues:
          - key: .json
        description: action-description
        wait:
          cluster: # Only one of cluster / network can be used
            kind: pod
            name: my-pod
            namespace: pod-ns
            condition: ready
          network:
            protocol: http
            address: github.com
            code: 200
constants:
- name: CONSTANT
  value: constant-value
  description: constant-value
  autoIndent: false
  pattern: ".+"
variables:
- name: VAR
  sensitive: false
  autoIndent: true
  pattern: ".+"
  type: raw
  description: var
  default: whatever
  prompt: false
